apiVersion: v1
kind: Secret
metadata:
   name: postgres-secret
type: Opaque
data:
   password: YWJjMTIzNDU=
---
kind: Service
apiVersion: v1
metadata:
  name: postgres-svc
spec:
  type: ExternalName
  externalName: postgres-svc.postgres.svc.cluster.local
  ports:
  - port: 5432
