image:
  tag: "v2.5.2"

deployment:
  kind: DaemonSet
  
additionalArguments:
- "--entryPoints.postgres.address=:5432/tcp"
- "--entryPoints.mongodb.address=:27017/tcp"
- "--entryPoints.redis.address=:6379/tcp"

ports:
  postgres:
    port: 5432
    expose: true
    exposedPort: 5432
    protocol: TCP
  mongodb:
    port: 27017
    expose: true
    exposedPort: 27017
    protocol: TCP
  redis:
    port: 6379
    expose: true
    exposedPort: 6379
    protocol: TCP
