# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

BoxName = "generic/ubuntu2004"
BoxVersion = "3.4.2"
AddedVal = 0

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap-k8s.sh"

  # Kubernetes Master Server
  config.vm.define "kmaster11#{1 + AddedVal}" do |node|
  
    node.vm.box               = BoxName
    node.vm.box_check_update  = false
    node.vm.box_version       = BoxVersion
    node.vm.hostname          = "kmaster11#{1 + AddedVal}"

    node.vm.network :public_network, :dev => "br0", :mode => "bridge", :type => "bridge", ip: "192.168.100.11#{1 + AddedVal}"
 
    node.vm.provider :libvirt do |v|
      v.memory  = 2048
      v.nested  = true
      v.cpus    = 2
    end
  
  end


  # Kubernetes Worker Nodes
  NodeCount = 1

  (1..NodeCount).each do |i|

    config.vm.define "kworker12#{i + AddedVal}" do |node|

      node.vm.box               = BoxName
      node.vm.box_check_update  = false
      node.vm.box_version       = BoxVersion
      node.vm.hostname          = "kworker12#{i + AddedVal}"

      node.vm.network :public_network, :dev => "br0", :mode => "bridge", :type => "bridge", ip: "192.168.100.12#{i + AddedVal}"

      node.vm.provider :libvirt do |v|
        v.memory  = 3072
        v.nested  = true
        v.cpus    = 2
      end

    end

  end

end
