namespace: argocd-app-runner
commonLabels:
  env: dev
  app: runner
namePrefix: runner-
resources:
- pvc.yaml
- deployment.yaml

configMapGenerator:
- name: config
  literals:
  - GITHUB_PAT=YOUR_GITHUB_ACCESS_TOKEN
  - GITHUB_OWNER=cams7
  - GITHUB_REPOSITORY=argocd-app
  - RUNNER_LABELS=dev,k8s,argocd-app
  - DOCKER_HOST=tcp://192.168.100.13:2375
