namespace: github-actions-runner
commonLabels:
  env: dev
  app: runner
namePrefix: runner-
resources:
- pvc.yaml
- deployment.yaml

configMapGenerator:
- name: config
  literals:
  - GITHUB_PAT=YOUR_GITHUB_ACCESS_TOKEN
  - GITHUB_OWNER=YOUR_GITHUB_USERNAME
  - GITHUB_REPOSITORY=YOUR_GITHUB_REPOSITORY
  - RUNNER_LABELS=dev,k8s
  - DOCKER_HOST=tcp://192.168.100.13:2375
